### ISSUE TITLE
Error I got Attempting to Run Script, Login Credentials were switched twice with same error

### ISSUE THREAD

**Issue by gpicon6** [ayyitsc9/nike-account-resetter#1]
[2021-02-23 19:57:50] Logging in...
[2021-02-23 19:57:51] Failed to log in! Error : b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'
Traceback (most recent call last):
  File "C:\Users\gpico\Desktop\nike-account-resetter-main\app.py", line 411, in <module>
    for mail in email.fetch(reverse=True, limit=email_limit):
  File "C:\Users\gpico\AppData\Local\Programs\Python\Python38-32\lib\site-packages\imap_tools\mailbox.py", line 100, in fetch
    nums = tuple((reversed if reverse else iter)(self.search(criteria, charset)))[limit_range]
  File "C:\Users\gpico\AppData\Local\Programs\Python\Python38-32\lib\site-packages\imap_tools\mailbox.py", line 60, in search
    search_result = self.box.search(charset, encoded_criteria)
  File "C:\Users\gpico\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 723, in search
    typ, dat = self._simple_command(name, 'CHARSET', charset, *criteria)
  File "C:\Users\gpico\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Users\gpico\AppData\Local\Programs\Python\Python38-32\lib\imaplib.py", line 943, in _command
    raise self.error("command %s illegal in state %s, "
imaplib.IMAP4.error: command SEARCH illegal in state NONAUTH, only allowed in states SELECTED
>>> 

Any Idea for a solution?

**Comment by ayyitsc9** [comment]
This is the fix
- Disable 2FA
- Change password
- Enable imap and less secure app access
(After running you should disable imap/ less secure app access and reenable 2fa if you'd like)
If you want to leave 2fa on, you may try this https://support.google.com/accounts/answer/185833?hl=en
